### ISSUE TITLE
'Quickstart' notebook outputs an error

### ISSUE THREAD

**Issue by rbardenet** [google/autobound#11]
Thanks for the interesting work! When I tried to run your `quickstart.ipynb` notebook, I got an error message at the second cell of code, where the first call to your library is made
```
bounds = ab.taylor_bounds(f, max_degree=2)(x0, trust_region)
```
The error shows up both on the "colab" link I followed from your github repo (with jax 0.4.20), and on my machine (with jax 0.4.19). The error reads
```
AttributeError: module 'jax' has no attribute 'abstract_arrays'
```

**Comment by mstreeter** [comment]
Thanks for reporting this! I'll push a fix soon.

**Comment by mstreeter** [comment]
This is fixed now.
