### ISSUE TITLE
Quickstart Notebook Error

### ISSUE THREAD

**Issue by waite116** [google/autobound#12]
Hi! 

This seems to be an awesome tool for Taylor Models, but I am having trouble using it from the start. I have tried following the quickstart model both in google colab notebook as well as on my local Windows and Linux machines, but to no avail. Any ideas on what might be causing this?

`
import autobound.jax as ab
import jax.numpy as jnp

f = lambda x: 1.5 * jnp.exp(3 * x) - 25*x**2
x0 = .5
trust_region = (0, 1)

bounds = ab.taylor_bounds(f, max_degree=2)(x0, trust_region)
bounds.coefficients'

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-13-23746a01b46f>](https://localhost:8080/#) in <cell line: 8>()
      6 trust_region = (0, 1)
      7 # Compute quadratic upper and lower bounds on f.
----> 8 bounds = ab.taylor_bounds(f, max_degree=2)(x0, trust_region)
      9 bounds.coefficients  # == (f(x0), f'(x0), <an interval>)

5 frames
[/usr/local/lib/python3.10/dist-packages/autobound/jax/jaxpr_editor.py](https://localhost:8080/#) in vertex_to_var_or_literal(vertex)
    170     if vertex[0]:
    171       _, count, suffix, aval = vertex
--> 172       if count not in count_to_var:
    173         count_to_var[count] = jax.core.Var(count, suffix, aval)
    174       return count_to_var[count]

TypeError: Var.__init__() takes 3 positional arguments but 4 were given

**Comment by waite116** [comment]
It seems that autograd does not work with the newest versions of jax, jaxlib, and typing_extensions. Instead, I rolled back versions to fall 2023 releases, and it works now.

**Comment by jack-mcivor** [comment]
> It seems that autograd does not work with the newest versions of jax, jaxlib, and typing_extensions
It would be best to supply an upper bound constraint to these dependencies
