### ISSUE TITLE
Usage fails without explicitly installing typing_extensions

### ISSUE THREAD

**Issue by jack-mcivor** [google/autobound#5]
To recreate, start a fresh environment and
```bash
pip install autobound `jax[cpu]`
python -c "import autobound.jax as ab"
```

`ModuleNotFoundError: No module named 'typing_extensions'` is raised

**Comment by jack-mcivor** [comment]
Fixed in https://github.com/google/autobound/pull/4

**Comment by mstreeter** [comment]
Thanks for fixing this!
